name: DockerWorkflow

on:
  push:
    branches:
      - develop
      - feature/*

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Test the Docker Image
      run: make test
    
    - name: Build the Docker image
      run: make build
      

      
      
      
